import { buildFundamentalAnalysisReport } from '../fundamentals/fundamentalAnalysis.js';
import { buildDcfModel, buildHybridBiotechModel, buildRiskAdjustedPipelineModel, classifyModelType } from '../financialModeling.js';
import { synthesizeEvidence } from '../synthesis/evidenceSynthesis.js';
import { generateStructuredThesisDraft } from '../ai/thesisDrafting.js';

const FORBIDDEN = ['buy','sell','guaranteed','certain','will go up','risk-free'];
const clean = (s='') => FORBIDDEN.reduce((t,w)=>String(t).replace(new RegExp(w,'ig'),'[redacted]'), s);
const step = (step, status, message, records_found=0, records_saved=0, warnings=[], data=null)=>({ step,status,message,records_found,records_saved,warnings,data });

export function buildResearchPlan(ticker, companyName, options={}){ return ['sec','market','fundamentals','financial_model','clinical_trials','pubmed','fda','infer_catalysts','source_snapshots',options.createDraftThesis?'draft_thesis':null,options.runSynthesis?'synthesis':null].filter(Boolean); }
export async function runSecStep(ctx){ try{ const j=await fetch(`${ctx.base}/api/sec/filings?ticker=${ctx.ticker}`).then(r=>r.json()); const a=j.filings||[]; return step('sec',a.length?'success':'partial','SEC step completed',a.length,0,a.length?[]:['No SEC filings returned.'],a);}catch(e){return step('sec','failed',String(e.message||e),0,0,['SEC step failed'],[]);} }
export async function runMarketDataStep(ctx){ try{ const j=await fetch(`${ctx.base}/api/market/refresh`,{method:'POST',body:JSON.stringify({ticker:ctx.ticker,range:'6mo'})}).then(r=>r.json()); return step('market',j?.quote?'success':'partial','Market step completed',j?.quote?1:0,0,j?.quote?[]:['Missing market snapshot'],j);}catch(e){return step('market','failed',String(e.message||e),0,0,['Market step failed'],{});} }
export async function runFundamentalsStep(ctx){ try{ const report=buildFundamentalAnalysisReport({ ticker:ctx.ticker, companyName:ctx.companyName, secFilings:ctx.secFilings||[], marketData:ctx.marketData||{}, pipeline:ctx.trials||[] }); return step('fundamentals','success','Fundamentals analyzed',1,0,[],report);}catch(e){return step('fundamentals','failed',String(e.message||e),0,0,['Fundamentals failed'],null);} }
export async function runClinicalTrialsStep(ctx){ try{ const j=await fetch(`${ctx.base}/api/clinical-trials/search?ticker=${ctx.ticker}`).then(r=>r.json()); const a=j.trials||[]; return step('clinical_trials',a.length?'success':'partial','ClinicalTrials step completed',a.length,0,a.length?[]:['No trial records found'],a);}catch(e){return step('clinical_trials','failed',String(e.message||e),0,0,['ClinicalTrials failed'],[]);} }
export function buildPubMedQuery(ticker, companyName, trials=[]){ const t=trials[0]||{}; return `${(t.interventions||[])[0]||ticker} ${(t.conditions||[])[0]||companyName||ticker} ${(t.keywords||[])[0]||'mechanism endpoint safety'}`.trim(); }
export async function runPubMedStep(ctx){ try{ const query=buildPubMedQuery(ctx.ticker,ctx.companyName,ctx.trials||[]); const j=await fetch(`${ctx.base}/api/pubmed/ingest`,{method:'POST',body:JSON.stringify({ticker:ctx.ticker,query,context:{drug:(ctx.trials?.[0]?.interventions||[])[0]||ctx.ticker},limit:ctx.options.limitPerSource||5})}).then(r=>r.json()); const a=j.articles||[]; return step('pubmed',a.length?'success':'partial','PubMed step completed',a.length,0,a.length?[]:['No PubMed records found'],{query,articles:a});}catch(e){return step('pubmed','failed',String(e.message||e),0,0,['PubMed failed'],{articles:[]});} }
export function buildFdaQuery(ticker, companyName, trials=[]){ const t=trials[0]||{}; return `${(t.interventions||[])[0]||ticker} ${(t.conditions||[])[0]||''} active ingredient class safety label`.trim(); }
export async function runFdaStep(ctx){ try{ const query=buildFdaQuery(ctx.ticker,ctx.companyName,ctx.trials||[]); const j=await fetch(`${ctx.base}/api/fda/ingest`,{method:'POST',body:JSON.stringify({ticker:ctx.ticker,query,context:{drug:(ctx.trials?.[0]?.interventions||[])[0]||ctx.ticker,company:ctx.companyName||ctx.ticker},limit:ctx.options.limitPerSource||5})}).then(r=>r.json()); const a=j.records||[]; return step('fda',a.length?'success':'partial','FDA step completed',a.length,0,a.length?[]:['No FDA records found (possible investigational asset).'],{query,records:a});}catch(e){return step('fda','failed',String(e.message||e),0,0,['FDA failed'],{records:[]});} }
export function runFinancialModelStep(ctx){ try{ const type=classifyModelType(ctx.fundamentals?.company_type, ctx.fundamentals, ctx.trials||[]); const assumptions={ ticker:ctx.ticker,revenue:ctx.fundamentals?.financial_snapshot?.revenue,cash:ctx.fundamentals?.financial_snapshot?.cash_and_equivalents,debt:ctx.fundamentals?.financial_snapshot?.total_debt,current_price:ctx.marketData?.quote?.price,shares_outstanding:ctx.marketData?.quote?.shares_outstanding,assets:(ctx.trials||[]).slice(0,3).map(t=>({drug_name:(t.interventions||[])[0]||'missing',indication:(t.conditions||[])[0]||'missing',phase:t.phase||'missing',estimated_peak_sales:'user assumption required',probability_of_success:'user assumption required'}))}; const model = type==='dcf'?buildDcfModel(assumptions):type==='risk_adjusted_pipeline'?buildRiskAdjustedPipelineModel(assumptions):buildHybridBiotechModel(assumptions); return step('financial_model','success','Financial model generated',1,0,model.warnings||[],{model_type:type,...model}); }catch(e){ return step('financial_model','failed',String(e.message||e),0,0,['Financial model failed'],null);} }
export function inferCatalystsStep(ctx){ const c=(ctx.trials||[]).slice(0,3).map(t=>({ title:`Potential readout ${t.nct_id||'missing'}`, expected_date:t.primary_completion_date||'missing', catalyst_type:'trial_data' })); return step('infer_catalysts',c.length?'success':'partial','Catalyst inference complete',c.length,0,c.length?[]:['No catalyst inference'],c); }
export async function createSourceSnapshotsStep(ctx){ const snaps=[]; const p=(arr,mk)=>(arr||[]).slice(0,ctx.options.limitPerSource||5).forEach(x=>snaps.push(mk(x))); p(ctx.secFilings,f=>({source_type:'sec',title:`${f.filingType||'SEC'} ${f.filingDate||''}`.trim(),source_url:f.url||'missing',raw_text:JSON.stringify(f),ticker:ctx.ticker,user_id:ctx.userId})); p(ctx.trials,t=>({source_type:'clinical_trials',title:t.brief_title||t.nct_id||'trial',source_url:t.source_url||'missing',raw_text:JSON.stringify(t),ticker:ctx.ticker,user_id:ctx.userId})); p(ctx.pubmed,p1=>({source_type:'pubmed',title:p1.title||p1.pmid||'pubmed',source_url:p1.source_url||'missing',raw_text:p1.abstract||'',ticker:ctx.ticker,user_id:ctx.userId})); p(ctx.fda,f=>({source_type:'fda',title:f.title||'fda',source_url:f.source_url||'missing',raw_text:JSON.stringify(f),ticker:ctx.ticker,user_id:ctx.userId})); if(ctx.marketData?.quote) snaps.push({source_type:'market_data',title:`Market ${ctx.ticker}`,source_url:'missing',raw_text:JSON.stringify(ctx.marketData.quote),ticker:ctx.ticker,user_id:ctx.userId}); if(ctx.fundamentals) snaps.push({source_type:'fundamentals',title:`Fundamentals ${ctx.ticker}`,source_url:'missing',raw_text:JSON.stringify(ctx.fundamentals),ticker:ctx.ticker,user_id:ctx.userId}); if(ctx.financialModel) snaps.push({source_type:'financial_model',title:`Financial model ${ctx.ticker}`,source_url:'missing',raw_text:JSON.stringify(ctx.financialModel),ticker:ctx.ticker,user_id:ctx.userId}); return step('source_snapshots',snaps.length?'success':'partial','Source snapshots prepared',snaps.length,snaps.length,[],snaps); }
export function buildResearchPacketSummary(ctx){ const f=ctx.fundamentals||{}; return { company_overview:clean(`Public-source research packet for ${ctx.ticker}.`), fundamental_context:clean(`Facts: company type ${f.company_type||'missing'}. Interpretations: quality ${f.fundamental_quality?.overall_label||'missing'}.`), valuation_context:clean(`Facts: model ${ctx.financialModel?.model_type||'missing'} intrinsic/share ${ctx.financialModel?.intrinsic_value_per_share||'missing'}. Interpretations: model output depends heavily on assumptions.`), financial_risk:f.biotech_specific_metrics?.dilution_risk||'missing', clinical_pipeline:(ctx.trials||[]).slice(0,3).map(t=>t.brief_title||t.nct_id||'missing'), scientific_context:(ctx.pubmed||[]).slice(0,3).map(p=>p.title||'missing'), regulatory_context:(ctx.fda||[]).slice(0,3).map(x=>x.title||'missing'), market_context:ctx.marketData?.quote?`Approximate quote ${ctx.marketData.quote.price||'missing'}`:'missing', catalyst_context:(ctx.catalysts||[]).slice(0,3).map(c=>c.title||'missing'), key_risks:[...(f.key_risks||[]), ...((ctx.financialModel?.warnings)||[])].filter(Boolean).map(clean).slice(0,8), missing_data:[...(f.missing_data||[]), ...(ctx.fda||[]).length?[]:['fda'], ...(ctx.pubmed||[]).length?[]:['pubmed'], ...(ctx.financialModel?.missing_fields||[])], suggested_follow_up_questions:['Review before using in thesis.','Which assumptions require user edits in valuation model?','Run synthesis after thesis drafting.'] }; }
export async function optionallyDraftThesisStep(ctx){ if(!ctx.options.createDraftThesis) return step('draft_thesis','skipped','Skipped',0,0,[],null); try{ const selectedSources=(ctx.snapshots||[]).slice(0,10).map(s=>({source_type:s.source_type,title:s.title,url:s.source_url,summary:s.raw_text,metadata:{}})); const res=await generateStructuredThesisDraft({ticker:ctx.ticker,companyName:ctx.companyName,selectedSources,draftPreferences:{tone:'conservative',includeFollowUpQuestions:true},marketContext:ctx.marketData||{}}); return step('draft_thesis',res.validation.ok?'success':'partial','Draft thesis generated',1,0,res.validation.ok?[]:res.validation.issues,res);}catch(e){return step('draft_thesis','failed',String(e.message||e),0,0,['Draft thesis failed'],null);} }
export function optionallyRunSynthesisStep(ctx){ if(!ctx.options.runSynthesis) return step('synthesis','skipped','Skipped',0,0,[],null); if(!ctx.draftThesis?.draft) return step('synthesis','partial','No draft thesis available for synthesis',0,0,['Missing thesis input'],null); const s=synthesizeEvidence({ thesis:ctx.draftThesis.draft, selectedSources:(ctx.snapshots||[]).map(x=>({source_type:x.source_type})), marketData:ctx.marketData||{}, catalyst:null }); return step('synthesis','success','Synthesis generated',1,0,[],s); }

export async function runCompanyResearchPacket(input){
  const ticker=String(input.ticker||'').toUpperCase(); const companyName=input.companyName||ticker;
  const options={ includeSec:true, includeMarketData:true, includeFundamentals:true, includeFinancialModel:true, includeClinicalTrials:true, includePubMed:true, includeFda:true, inferCatalysts:true, createSourceSnapshots:true, createDraftThesis:false, runSynthesis:true, limitPerSource:5, ...(input.options||{}) };
  const ctx={...input,ticker,companyName,options,base:input.base||'http://localhost:3000'}; const steps=[];
  const sec=options.includeSec?await runSecStep(ctx):step('sec','skipped','Skipped'); steps.push(sec); ctx.secFilings=sec.data||[];
  const market=options.includeMarketData?await runMarketDataStep(ctx):step('market','skipped','Skipped'); steps.push(market); ctx.marketData=market.data||{};
  const trials=options.includeClinicalTrials?await runClinicalTrialsStep(ctx):step('clinical_trials','skipped','Skipped'); steps.push(trials); ctx.trials=trials.data||[];
  const fund=options.includeFundamentals?await runFundamentalsStep(ctx):step('fundamentals','skipped','Skipped'); steps.push(fund); ctx.fundamentals=fund.data;
  const fm=options.includeFinancialModel?runFinancialModelStep(ctx):step('financial_model','skipped','Skipped'); steps.push(fm); ctx.financialModel=fm.data;
  const pub=options.includePubMed?await runPubMedStep(ctx):step('pubmed','skipped','Skipped'); steps.push(pub); ctx.pubmed=pub.data?.articles||pub.data||[];
  const fda=options.includeFda?await runFdaStep(ctx):step('fda','skipped','Skipped'); steps.push(fda); ctx.fda=fda.data?.records||fda.data||[];
  const cat=options.inferCatalysts?inferCatalystsStep(ctx):step('infer_catalysts','skipped','Skipped'); steps.push(cat); ctx.catalysts=cat.data||[];
  const snaps=options.createSourceSnapshots?await createSourceSnapshotsStep(ctx):step('source_snapshots','skipped','Skipped'); steps.push(snaps); ctx.snapshots=snaps.data||[];
  const draft=await optionallyDraftThesisStep(ctx); steps.push(draft); ctx.draftThesis=draft.data;
  const syn=optionallyRunSynthesisStep(ctx); steps.push(syn); ctx.synthesis=syn.data;
  const summary=buildResearchPacketSummary(ctx); const failed=steps.filter(s=>s.status==='failed').length; const partial=steps.filter(s=>s.status==='partial').length;
  return { ticker, companyName, status:failed===steps.length?'failed':(failed||partial?'partial':'success'), steps, sources_created:ctx.snapshots||[], catalysts_created_or_suggested:ctx.catalysts||[], fundamental_report_id:ctx.fundamentals?.id, financial_model_id:ctx.financialModel?.id, draft_thesis_id:ctx.draftThesis?.draft?.id, synthesis_id:ctx.synthesis?.id, research_packet_summary:summary, warnings:steps.flatMap(s=>s.warnings||[]), missing_data:summary.missing_data||[] };
}
