alter table clinical_trials add column if not exists ticker text;
alter table clinical_trials add column if not exists company_id uuid references companies(id) on delete set null;
alter table clinical_trials add column if not exists sponsor text;
alter table clinical_trials add column if not exists collaborators text[];
alter table clinical_trials add column if not exists conditions text[];
alter table clinical_trials add column if not exists interventions text[];
alter table clinical_trials add column if not exists drug_candidates text[];
alter table clinical_trials add column if not exists study_type text;
alter table clinical_trials add column if not exists allocation text;
alter table clinical_trials add column if not exists masking text;
alter table clinical_trials add column if not exists primary_purpose text;
alter table clinical_trials add column if not exists primary_completion_date date;
alter table clinical_trials add column if not exists primary_endpoints jsonb;
alter table clinical_trials add column if not exists secondary_endpoints jsonb;
alter table clinical_trials add column if not exists locations jsonb;
alter table clinical_trials add column if not exists retrieved_at timestamptz;
alter table clinical_trials add column if not exists raw_json jsonb;
alter table clinical_trials add column if not exists missing_fields text[];
alter table clinical_trials add column if not exists updated_at timestamptz default now();
create unique index if not exists clinical_trials_nct_id_key on clinical_trials(nct_id);
